In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_excel("C:/Users/User/Desktop/fr/ksss/grdata3.xlsx")

In [3]:
print(type(data))
print(data.shape)
print(data.columns.values)

<class 'pandas.core.frame.DataFrame'>
(29, 17)
['Класс' 'ФИО' 'Всемирная история' 'Естествознание' 'Инностранный язык'
 'Информатика и ИИ' 'История Казахстана' 'Казахский язык и литература'
 'Математика' 'Музыка' 'Ознакомление с окружающим миром'
 'Русская литература' 'Русский язык' 'Физическая культура'
 'Художественный труд' 'Ср. Балл' 'Рейтинг']

In [4]:
data.head(50)

,Класс,ФИО,Всемирная история,Естествознание,Инностранный язык,Информатика и ИИ,История Казахстана,Казахский язык и литература,Математика,Музыка,Ознакомление с окружающим миром,Русская литература,Русский язык,Физическая культура,Художественный труд,Ср. Балл,Рейтинг
0,5А,Аймагамбетов \nЭлисар \nКуанышевич,4,4,4,5,4,4,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.11,5
1,5А,Алазова \nМилана \nНазировна,3,4,4,4,3,4,4,ЗЧ,ЗЧ,5,4,ЗЧ,ЗЧ,3.89,6
2,5А,Белозерова \nМилана \nВадимовна,4,5,5,4,4,5,4,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,4.56,3
3,5А,Досанова \nАймина \nСагадатовна,5,5,5,5,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,5.00,1
4,5А,Клементьев \nРодион \nСергеевич,5,5,5,5,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,5.00,1
5,5А,Ренат \nРауда,3,3,3,4,3,3,3,ЗЧ,ЗЧ,3,3,ЗЧ,ЗЧ,3.11,10
6,5А,Рысбеков \nДаниал \nАмирович,3,3,3,4,4,3,3,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,3.44,8
7,5А,Саутиева \nСальма \nБагаудиновна,3,3,3,4,3,3,3,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,3.33,9
8,5А,Сергеев \nГлеб \nИгоревич,4,4,4,4,4,4,4,ЗЧ,ЗЧ,5,4,ЗЧ,ЗЧ,4.11,5
9,5А,Сулеев \nРуслан \nАндреевич,4,4,4,4,4,4,4,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,4.22,4
10,5А,Султан \nАйсултана,4,3,3,4,3,3,3,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,3.44,8
11,5А,Тагиева \nЭстер \nГейдаровна,3,4,4,4,3,3,3,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,3.56,7
12,5А,Токтаров \nБектемир \nОлжасович,4,4,5,5,4,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,4.67,2
13,5Б,Альжанов \nСанжар \nНурланович,4,3,4,5,4,4,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.00,6
14,5Б,Верещака \nАнтонина \nСеменовна,4,4,4,5,4,5,5,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.33,3
15,5Б,Козачков \nДавид \nМихайлович,4,4,5,4,4,4,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.11,5
16,5Б,Нухжан \nИльяс \nМанасұлы,4,4,4,4,4,5,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.11,5
17,5Б,Распопова \nНина \nАлександровна,5,4,5,4,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,4.78,2
18,5Б,Рогозин \nМатвей \nАнтонович,4,4,4,4,4,5,5,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.22,4
19,5Б,Тё \nАнгелина \nВладиславовна,5,5,5,5,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,5.00,1
20,5Б,Турар \nЭмирлан \nАйбекұлы,4,4,4,4,3,3,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,3.78,7
21,5В,Галимова \nАмина \nМарленовна,4,4,4,4,4,4,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.00,4
22,5В,Ибраева \nЖания \nРустамовна,5,5,5,5,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,5.00,1
23,5В,Касиманова \nРайана \nАзатовна,4,4,5,4,4,4,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.11,3
24,5В,Касюк \nРостислав \nИгоревич,4,4,4,4,4,4,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.00,4
25,5В,Олжабай \nАйым \nАтаханқызы,5,5,5,5,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,5.00,1
26,5В,Рамазанова \nМилана \nАндреевна,5,5,5,5,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,5.00,1
27,5В,Саутбаева \nАиша \nАзатқызы,5,5,4,5,4,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,4.78,2
28,5В,Чакмин \nДаниэль \nАлександрович,4,4,4,4,4,4,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.00,4

In [5]:
data['Класс'].unique()

array(['5А', '5Б', '5В'], dtype=object)

In [6]:
Dict={'5А':1, '5Б':2, '5В':3}

In [7]:
data['Класс']=data['Класс'].map(Dict)

In [8]:
data['Класс']

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    3
22    3
23    3
24    3
25    3
26    3
27    3
28    3
Name: Класс, dtype: int64

In [9]:
data.head(20)

,Класс,ФИО,Всемирная история,Естествознание,Инностранный язык,Информатика и ИИ,История Казахстана,Казахский язык и литература,Математика,Музыка,Ознакомление с окружающим миром,Русская литература,Русский язык,Физическая культура,Художественный труд,Ср. Балл,Рейтинг
0,1,Аймагамбетов \nЭлисар \nКуанышевич,4,4,4,5,4,4,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.11,5
1,1,Алазова \nМилана \nНазировна,3,4,4,4,3,4,4,ЗЧ,ЗЧ,5,4,ЗЧ,ЗЧ,3.89,6
2,1,Белозерова \nМилана \nВадимовна,4,5,5,4,4,5,4,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,4.56,3
3,1,Досанова \nАймина \nСагадатовна,5,5,5,5,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,5.00,1
4,1,Клементьев \nРодион \nСергеевич,5,5,5,5,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,5.00,1
5,1,Ренат \nРауда,3,3,3,4,3,3,3,ЗЧ,ЗЧ,3,3,ЗЧ,ЗЧ,3.11,10
6,1,Рысбеков \nДаниал \nАмирович,3,3,3,4,4,3,3,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,3.44,8
7,1,Саутиева \nСальма \nБагаудиновна,3,3,3,4,3,3,3,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,3.33,9
8,1,Сергеев \nГлеб \nИгоревич,4,4,4,4,4,4,4,ЗЧ,ЗЧ,5,4,ЗЧ,ЗЧ,4.11,5
9,1,Сулеев \nРуслан \nАндреевич,4,4,4,4,4,4,4,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,4.22,4
10,1,Султан \nАйсултана,4,3,3,4,3,3,3,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,3.44,8
11,1,Тагиева \nЭстер \nГейдаровна,3,4,4,4,3,3,3,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,3.56,7
12,1,Токтаров \nБектемир \nОлжасович,4,4,5,5,4,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,4.67,2
13,2,Альжанов \nСанжар \nНурланович,4,3,4,5,4,4,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.00,6
14,2,Верещака \nАнтонина \nСеменовна,4,4,4,5,4,5,5,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.33,3
15,2,Козачков \nДавид \nМихайлович,4,4,5,4,4,4,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.11,5
16,2,Нухжан \nИльяс \nМанасұлы,4,4,4,4,4,5,4,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.11,5
17,2,Распопова \nНина \nАлександровна,5,4,5,4,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,4.78,2
18,2,Рогозин \nМатвей \nАнтонович,4,4,4,4,4,5,5,ЗЧ,ЗЧ,4,4,ЗЧ,ЗЧ,4.22,4
19,2,Тё \nАнгелина \nВладиславовна,5,5,5,5,5,5,5,ЗЧ,ЗЧ,5,5,ЗЧ,ЗЧ,5.00,1

In [10]:
data['Всемирная история'].unique()

array([4, 3, 5], dtype=int64)

In [11]:
#m=np.mean(data['Всемирная история'])
m

NameError: name 'm' is not defined

In [ ]:
#Mediana=np.median(data['Всемирная история'])
#Mediana

In [ ]:
#data['Всемирная история']=data['Всемирная история'].fillna(m)

In [ ]:
k = data.drop(columns=['Музыка','Физическая культура','Художественный труд','Ознакомление с окружающим миром'])

In [ ]:
k.head(10)

In [ ]:
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

In [ ]:
import pandas as pd
import numpy as np

df = k.copy()
df = pd.DataFrame(df)

df['Ученик_ID'] = np.arange(1, len(df) + 1)


df = df.drop(columns=['Фамилия, Имя'], errors='ignore')

target = "Рейтинг"


X = df.drop(columns=[target])
y = pd.to_numeric(df[target], errors='coerce').fillna(df[target].mean())

In [ ]:
import pandas as pd
import numpy as np


X = pd.DataFrame(X)


categorical_cols = X.dtypes[X.dtypes == 'object'].index
numeric_cols = X.dtypes[X.dtypes != 'object'].index

print("Categorical columns:", categorical_cols)
print("Numeric columns:", numeric_cols)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline


df = k.copy()
df = pd.DataFrame(df)


df['Ученик_ID'] = np.arange(1, len(df) + 1)


df = df.drop(columns=['ФИО'], errors='ignore')

target = "Рейтинг"

X = df.drop(columns=[target])
y = pd.to_numeric(df[target], errors='coerce').fillna(df[target].mean())


categorical_cols = X.dtypes[X.dtypes == 'object'].index
numeric_cols = X.dtypes[X.dtypes != 'object'].index


numeric_transformer = "passthrough"
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_cols),
        ("cat", categorical_transformer, categorical_cols)
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)


model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ))
])


model.fit(X_train, y_train)


y_pred = model.predict(X_test)


mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)


plt.figure(figsize=(8,5))

plt.scatter(y_test, y_pred)

plt.plot([y.min(), y.max()],
         [y.min(), y.max()],
         linestyle='--')

plt.xlabel("Реальный рейтинг")
plt.ylabel("Прогноз рейтинга")
plt.title("Прогноз рейтинга учеников")

plt.grid()
plt.show()

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

df = k.copy()


df['Ученик_ID'] = np.arange(1, len(df) + 1)

df = df.drop(columns=['ФИО'])


target = "Рейтинг"

X = df.drop(columns=[target])
y = pd.to_numeric(df[target], errors='coerce')

y = y.fillna(y.mean())


categorical_cols = X.select_dtypes(include=['object']).columns
numeric_cols = X.select_dtypes(exclude=['object']).columns


numeric_transformer = "passthrough"
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_cols),
        ("cat", categorical_transformer, categorical_cols)
    ])



X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)



model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ))
])


model.fit(X_train, y_train)


y_pred = model.predict(X_test)


mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)


plt.figure(figsize=(8,5))

plt.scatter(y_test, y_pred)

plt.plot([y.min(), y.max()],
         [y.min(), y.max()],
         linestyle='--')

plt.xlabel("Реальный рейтинг")
plt.ylabel("Прогноз рейтинга")
plt.title("Прогноз рейтинга учеников")

plt.grid()
plt.show()

In [ ]:
from sklearn.model_selection import RandomizedSearchCV


param_dist = {
    'regressor__n_estimators': [300, 500, 700],
    'regressor__max_depth': [10, 15, 20, None],
    'regressor__min_samples_split': [2, 5, 10]
}

random_search = RandomizedSearchCV(
    model,
    param_distributions=param_dist,
    n_iter=5,
    cv=3,
    scoring='r2',
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train)


best_model = random_search.best_estimator_

print("\nЛучшие параметры:")
print(random_search.best_params_)



y_pred = best_model.predict(X_test)


print("\n===== Финальные метрики =====")
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))



plt.figure(figsize=(8,5))


plt.scatter(range(len(y_test)),
            y_test,
            label="Реальный результат")


plt.scatter(range(len(y_pred)),
            y_pred,
            label="Прогноз",
            alpha=0.7)

plt.xlabel("Индекс ученика")
plt.ylabel("Рейтинг")
plt.title("Реальные оценки vs Прогнозирование")

plt.legend()
plt.grid()

plt.show()

In [ ]:
from sklearn.metrics import r2_score


train_pred = best_model.predict(X_train)
test_pred = best_model.predict(X_test)

r2_train = r2_score(y_train, train_pred)
r2_test = r2_score(y_test, test_pred)

print("R2 Train:", r2_train)
print("R2 Test:", r2_test)

if r2_train - r2_test > 0.05:
    print("⚠ Возможное переобучение")
else:
    print("✓ Переобучение не обнаружено")

In [ ]:
from sklearn.model_selection import learning_curve

train_sizes, train_scores, test_scores = learning_curve(
    best_model,
    X_train,
    y_train,
    cv=3,
    scoring='r2',
    n_jobs=-1
)

train_mean = train_scores.mean(axis=1)
test_mean = test_scores.mean(axis=1)

plt.figure(figsize=(8,5))

plt.plot(train_sizes, train_mean, label="Train Score")
plt.plot(train_sizes, test_mean, label="Validation Score")

plt.xlabel("Размер обучающей выборки")
plt.ylabel("R2 Score")
plt.title("Learning Curve")
plt.legend()
plt.grid()
plt.show()

In [ ]:
import numpy as np

baseline_score = best_model.score(X_test, y_test)

feature_names = X_test.columns
importances = []

for col in feature_names:
    X_test_permuted = X_test.copy()
    X_test_permuted[col] = np.random.permutation(X_test_permuted[col])
    
    permuted_score = best_model.score(X_test_permuted, y_test)
    importance = baseline_score - permuted_score
    importances.append(importance)

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

top_features = importance_df.head(10)

plt.figure(figsize=(8,5))
plt.barh(top_features["Feature"], top_features["Importance"])
plt.gca().invert_yaxis()
plt.title("Manual Permutation Importance")
plt.grid()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111, projection='3d')

index = np.arange(len(y_test))


ax.scatter(index, y_test, y_test,
           color='blue', label='Реальные')

ax.scatter(index, y_test, y_pred,
           color='red', label='Прогноз')

ax.set_xlabel("Индекс ученика")
ax.set_ylabel("Реальный рейтинг")
ax.set_zlabel("Значение")

ax.set_title("3D: Реальные vs Прогноз")
ax.legend()

plt.show()

In [ ]:
fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111, projection='3d')

residuals = y_test - y_pred
index = np.arange(len(residuals))

sc = ax.scatter(index, y_pred, residuals,
                c=residuals,
                cmap='coolwarm')

ax.set_xlabel("Индекс")
ax.set_ylabel("Прогноз")
ax.set_zlabel("Ошибка")

ax.set_title("3D: Ошибки модели")

fig.colorbar(sc, shrink=0.5, aspect=5)

plt.show()

In [ ]:
feature1 = X_test.columns[0]
feature2 = X_test.columns[1]

x1 = X_test[feature1]
x2 = X_test[feature2]

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111, projection='3d')

sc = ax.scatter(x1, x2, y_pred,
                c=y_pred,
                cmap='viridis')

ax.set_xlabel(feature1)
ax.set_ylabel(feature2)
ax.set_zlabel("Прогноз рейтинга")

ax.set_title("3D: Влияние двух предметов")

fig.colorbar(sc, shrink=0.5, aspect=5)

plt.show()

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np


gb_model = GradientBoostingRegressor(
    n_estimators=200,
    random_state=42
)

gb_model.fit(X_train, y_train)


rf_pred = model.predict(X_test)
gb_pred = gb_model.predict(X_test)

rf_mae = mean_absolute_error(y_test, rf_pred)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
rf_r2 = r2_score(y_test, rf_pred)

gb_mae = mean_absolute_error(y_test, gb_pred)
gb_rmse = np.sqrt(mean_squared_error(y_test, gb_pred))
gb_r2 = r2_score(y_test, gb_pred)

print("Random Forest:")
print("MAE:", rf_mae)
print("RMSE:", rf_rmse)
print("R2:", rf_r2)

print("\nGradient Boosting:")
print("MAE:", gb_mae)
print("RMSE:", gb_rmse)
print("R2:", gb_r2)

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.scatter(y_test, rf_pred, color='blue', alpha=0.6, label='Random Forest')
plt.scatter(y_test, gb_pred, color='red', alpha=0.6, label='Gradient Boosting')

plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color='black', linestyle='--', label='Ideal')

plt.xlabel("Реальные значения")
plt.ylabel("Прогноз")
plt.title("Сравнение моделей")
plt.legend()
plt.grid()

plt.show()

In [ ]:
metrics = ['MAE', 'RMSE', 'R2']

rf_scores = [rf_mae, rf_rmse, rf_r2]
gb_scores = [gb_mae, gb_rmse, gb_r2]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(8,6))

plt.bar(x - width/2, rf_scores, width, label='Random Forest', color='blue')
plt.bar(x + width/2, gb_scores, width, label='Gradient Boosting', color='red')

plt.xticks(x, metrics)
plt.title("Сравнение метрик моделей")
plt.legend()
plt.grid(axis='y')

plt.show()

In [ ]:
rf_residuals = y_test - rf_pred
gb_residuals = y_test - gb_pred

plt.figure(figsize=(8,6))

plt.scatter(rf_pred, rf_residuals, color='blue', alpha=0.5, label='RF Residuals')
plt.scatter(gb_pred, gb_residuals, color='red', alpha=0.5, label='GB Residuals')

plt.axhline(0, color='black', linestyle='--')

plt.xlabel("Прогноз")
plt.ylabel("Ошибка")
plt.title("Сравнение ошибок моделей")
plt.legend()
plt.grid()

plt.show()